# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cryptoswarm.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'cryptoswarm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ryptoswarm.proto\x12\x0b\x63ryptoswarm\"\x07\n\x05\x45mpty\"\x89\x01\n\x08Position\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04side\x18\x02 \x01(\t\x12\x0b\n\x03qty\x18\x03 \x01(\x01\x12\x13\n\x0b\x65ntry_price\x18\x04 \x01(\x01\x12\x12\n\nmark_price\x18\x05 \x01(\x01\x12\x16\n\x0eunrealized_pnl\x18\x06 \x01(\x01\x12\x11\n\tliq_price\x18\x07 \x01(\x01\"^\n\x11PositionsResponse\x12(\n\tpositions\x18\x01 \x03(\x0b\x32\x15.cryptoswarm.Position\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x01\x12\x0e\n\x06\x65quity\x18\x03 \x01(\x01\"f\n\x0b\x41gentStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0blast_symbol\x18\x02 \x01(\t\x12\x13\n\x0blast_output\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0f\n\x07last_ts\x18\x05 \x01(\x03\"?\n\x13\x41gentStatusResponse\x12(\n\x06\x61gents\x18\x01 \x03(\x0b\x32\x18.cryptoswarm.AgentStatus\",\n\nTradeEvent\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t2\xdf\x01\n\x0eTradingService\x12\x46\n\x10GetLivePositions\x12\x12.cryptoswarm.Empty\x1a\x1e.cryptoswarm.PositionsResponse\x12\x46\n\x0eGetAgentStatus\x12\x12.cryptoswarm.Empty\x1a .cryptoswarm.AgentStatusResponse\x12=\n\x0cStreamEvents\x12\x12.cryptoswarm.Empty\x1a\x17.cryptoswarm.TradeEvent0\x01\x42\x0fZ\r./proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cryptoswarm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\r./proto;proto'
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_POSITION']._serialized_start=44
  _globals['_POSITION']._serialized_end=181
  _globals['_POSITIONSRESPONSE']._serialized_start=183
  _globals['_POSITIONSRESPONSE']._serialized_end=277
  _globals['_AGENTSTATUS']._serialized_start=279
  _globals['_AGENTSTATUS']._serialized_end=381
  _globals['_AGENTSTATUSRESPONSE']._serialized_start=383
  _globals['_AGENTSTATUSRESPONSE']._serialized_end=446
  _globals['_TRADEEVENT']._serialized_start=448
  _globals['_TRADEEVENT']._serialized_end=492
  _globals['_TRADINGSERVICE']._serialized_start=495
  _globals['_TRADINGSERVICE']._serialized_end=718
# @@protoc_insertion_point(module_scope)
