# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cryptoswarm_pb2 as cryptoswarm__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cryptoswarm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLivePositions = channel.unary_unary(
                '/cryptoswarm.TradingService/GetLivePositions',
                request_serializer=cryptoswarm__pb2.Empty.SerializeToString,
                response_deserializer=cryptoswarm__pb2.PositionsResponse.FromString,
                _registered_method=True)
        self.GetAgentStatus = channel.unary_unary(
                '/cryptoswarm.TradingService/GetAgentStatus',
                request_serializer=cryptoswarm__pb2.Empty.SerializeToString,
                response_deserializer=cryptoswarm__pb2.AgentStatusResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/cryptoswarm.TradingService/StreamEvents',
                request_serializer=cryptoswarm__pb2.Empty.SerializeToString,
                response_deserializer=cryptoswarm__pb2.TradeEvent.FromString,
                _registered_method=True)


class TradingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetLivePositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLivePositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLivePositions,
                    request_deserializer=cryptoswarm__pb2.Empty.FromString,
                    response_serializer=cryptoswarm__pb2.PositionsResponse.SerializeToString,
            ),
            'GetAgentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentStatus,
                    request_deserializer=cryptoswarm__pb2.Empty.FromString,
                    response_serializer=cryptoswarm__pb2.AgentStatusResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=cryptoswarm__pb2.Empty.FromString,
                    response_serializer=cryptoswarm__pb2.TradeEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cryptoswarm.TradingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cryptoswarm.TradingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLivePositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cryptoswarm.TradingService/GetLivePositions',
            cryptoswarm__pb2.Empty.SerializeToString,
            cryptoswarm__pb2.PositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cryptoswarm.TradingService/GetAgentStatus',
            cryptoswarm__pb2.Empty.SerializeToString,
            cryptoswarm__pb2.AgentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cryptoswarm.TradingService/StreamEvents',
            cryptoswarm__pb2.Empty.SerializeToString,
            cryptoswarm__pb2.TradeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
