// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: cryptoswarm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_cryptoswarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_cryptoswarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_cryptoswarm_proto_rawDescGZIP(), []int{0}
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          string                 `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"`
	Qty           float64                `protobuf:"fixed64,3,opt,name=qty,proto3" json:"qty,omitempty"`
	EntryPrice    float64                `protobuf:"fixed64,4,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	MarkPrice     float64                `protobuf:"fixed64,5,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	UnrealizedPnl float64                `protobuf:"fixed64,6,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	LiqPrice      float64                `protobuf:"fixed64,7,opt,name=liq_price,json=liqPrice,proto3" json:"liq_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_cryptoswarm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_cryptoswarm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_cryptoswarm_proto_rawDescGZIP(), []int{1}
}

func (x *Position) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Position) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Position) GetQty() float64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *Position) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *Position) GetMarkPrice() float64 {
	if x != nil {
		return x.MarkPrice
	}
	return 0
}

func (x *Position) GetUnrealizedPnl() float64 {
	if x != nil {
		return x.UnrealizedPnl
	}
	return 0
}

func (x *Position) GetLiqPrice() float64 {
	if x != nil {
		return x.LiqPrice
	}
	return 0
}

type PositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Equity        float64                `protobuf:"fixed64,3,opt,name=equity,proto3" json:"equity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionsResponse) Reset() {
	*x = PositionsResponse{}
	mi := &file_cryptoswarm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionsResponse) ProtoMessage() {}

func (x *PositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptoswarm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionsResponse.ProtoReflect.Descriptor instead.
func (*PositionsResponse) Descriptor() ([]byte, []int) {
	return file_cryptoswarm_proto_rawDescGZIP(), []int{2}
}

func (x *PositionsResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *PositionsResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *PositionsResponse) GetEquity() float64 {
	if x != nil {
		return x.Equity
	}
	return 0
}

type AgentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LastSymbol    string                 `protobuf:"bytes,2,opt,name=last_symbol,json=lastSymbol,proto3" json:"last_symbol,omitempty"`
	LastOutput    string                 `protobuf:"bytes,3,opt,name=last_output,json=lastOutput,proto3" json:"last_output,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	LastTs        int64                  `protobuf:"varint,5,opt,name=last_ts,json=lastTs,proto3" json:"last_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_cryptoswarm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cryptoswarm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_cryptoswarm_proto_rawDescGZIP(), []int{3}
}

func (x *AgentStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentStatus) GetLastSymbol() string {
	if x != nil {
		return x.LastSymbol
	}
	return ""
}

func (x *AgentStatus) GetLastOutput() string {
	if x != nil {
		return x.LastOutput
	}
	return ""
}

func (x *AgentStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentStatus) GetLastTs() int64 {
	if x != nil {
		return x.LastTs
	}
	return 0
}

type AgentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentStatus         `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatusResponse) Reset() {
	*x = AgentStatusResponse{}
	mi := &file_cryptoswarm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusResponse) ProtoMessage() {}

func (x *AgentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptoswarm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusResponse.ProtoReflect.Descriptor instead.
func (*AgentStatusResponse) Descriptor() ([]byte, []int) {
	return file_cryptoswarm_proto_rawDescGZIP(), []int{4}
}

func (x *AgentStatusResponse) GetAgents() []*AgentStatus {
	if x != nil {
		return x.Agents
	}
	return nil
}

type TradeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeEvent) Reset() {
	*x = TradeEvent{}
	mi := &file_cryptoswarm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeEvent) ProtoMessage() {}

func (x *TradeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cryptoswarm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeEvent.ProtoReflect.Descriptor instead.
func (*TradeEvent) Descriptor() ([]byte, []int) {
	return file_cryptoswarm_proto_rawDescGZIP(), []int{5}
}

func (x *TradeEvent) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TradeEvent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_cryptoswarm_proto protoreflect.FileDescriptor

const file_cryptoswarm_proto_rawDesc = "" +
	"\n" +
	"\x11cryptoswarm.proto\x12\vcryptoswarm\"\a\n" +
	"\x05Empty\"\xcc\x01\n" +
	"\bPosition\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04side\x18\x02 \x01(\tR\x04side\x12\x10\n" +
	"\x03qty\x18\x03 \x01(\x01R\x03qty\x12\x1f\n" +
	"\ventry_price\x18\x04 \x01(\x01R\n" +
	"entryPrice\x12\x1d\n" +
	"\n" +
	"mark_price\x18\x05 \x01(\x01R\tmarkPrice\x12%\n" +
	"\x0eunrealized_pnl\x18\x06 \x01(\x01R\runrealizedPnl\x12\x1b\n" +
	"\tliq_price\x18\a \x01(\x01R\bliqPrice\"z\n" +
	"\x11PositionsResponse\x123\n" +
	"\tpositions\x18\x01 \x03(\v2\x15.cryptoswarm.PositionR\tpositions\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12\x16\n" +
	"\x06equity\x18\x03 \x01(\x01R\x06equity\"\x94\x01\n" +
	"\vAgentStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vlast_symbol\x18\x02 \x01(\tR\n" +
	"lastSymbol\x12\x1f\n" +
	"\vlast_output\x18\x03 \x01(\tR\n" +
	"lastOutput\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x17\n" +
	"\alast_ts\x18\x05 \x01(\x03R\x06lastTs\"G\n" +
	"\x13AgentStatusResponse\x120\n" +
	"\x06agents\x18\x01 \x03(\v2\x18.cryptoswarm.AgentStatusR\x06agents\"<\n" +
	"\n" +
	"TradeEvent\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload2\xdf\x01\n" +
	"\x0eTradingService\x12F\n" +
	"\x10GetLivePositions\x12\x12.cryptoswarm.Empty\x1a\x1e.cryptoswarm.PositionsResponse\x12F\n" +
	"\x0eGetAgentStatus\x12\x12.cryptoswarm.Empty\x1a .cryptoswarm.AgentStatusResponse\x12=\n" +
	"\fStreamEvents\x12\x12.cryptoswarm.Empty\x1a\x17.cryptoswarm.TradeEvent0\x01B\x0fZ\r./proto;protob\x06proto3"

var (
	file_cryptoswarm_proto_rawDescOnce sync.Once
	file_cryptoswarm_proto_rawDescData []byte
)

func file_cryptoswarm_proto_rawDescGZIP() []byte {
	file_cryptoswarm_proto_rawDescOnce.Do(func() {
		file_cryptoswarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cryptoswarm_proto_rawDesc), len(file_cryptoswarm_proto_rawDesc)))
	})
	return file_cryptoswarm_proto_rawDescData
}

var file_cryptoswarm_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cryptoswarm_proto_goTypes = []any{
	(*Empty)(nil),               // 0: cryptoswarm.Empty
	(*Position)(nil),            // 1: cryptoswarm.Position
	(*PositionsResponse)(nil),   // 2: cryptoswarm.PositionsResponse
	(*AgentStatus)(nil),         // 3: cryptoswarm.AgentStatus
	(*AgentStatusResponse)(nil), // 4: cryptoswarm.AgentStatusResponse
	(*TradeEvent)(nil),          // 5: cryptoswarm.TradeEvent
}
var file_cryptoswarm_proto_depIdxs = []int32{
	1, // 0: cryptoswarm.PositionsResponse.positions:type_name -> cryptoswarm.Position
	3, // 1: cryptoswarm.AgentStatusResponse.agents:type_name -> cryptoswarm.AgentStatus
	0, // 2: cryptoswarm.TradingService.GetLivePositions:input_type -> cryptoswarm.Empty
	0, // 3: cryptoswarm.TradingService.GetAgentStatus:input_type -> cryptoswarm.Empty
	0, // 4: cryptoswarm.TradingService.StreamEvents:input_type -> cryptoswarm.Empty
	2, // 5: cryptoswarm.TradingService.GetLivePositions:output_type -> cryptoswarm.PositionsResponse
	4, // 6: cryptoswarm.TradingService.GetAgentStatus:output_type -> cryptoswarm.AgentStatusResponse
	5, // 7: cryptoswarm.TradingService.StreamEvents:output_type -> cryptoswarm.TradeEvent
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cryptoswarm_proto_init() }
func file_cryptoswarm_proto_init() {
	if File_cryptoswarm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cryptoswarm_proto_rawDesc), len(file_cryptoswarm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cryptoswarm_proto_goTypes,
		DependencyIndexes: file_cryptoswarm_proto_depIdxs,
		MessageInfos:      file_cryptoswarm_proto_msgTypes,
	}.Build()
	File_cryptoswarm_proto = out.File
	file_cryptoswarm_proto_goTypes = nil
	file_cryptoswarm_proto_depIdxs = nil
}
